# Generated by Django 5.2.12 on 2026-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerrequest',
            name='description',
        ),
        migrations.AddField(
            model_name='employerrequest',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employerrequest',
            name='company_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employerrequest',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
